server:
  port: 8090
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:sksb_test;MODE=MYSQL
    username: root
    password:
    driver-class-name: org.h2.Driver
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://127.0.0.1:3306/sksb_dev
#    username: root
#    password:

